spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/mydb
    username: mydb
    password: mydb
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8081
